# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('date', models.DateField(default='1971-01-01', primary_key=True, serialize=False)),
                ('incoming_calls', models.IntegerField(default=0)),
                ('unanswered_calls', models.IntegerField(default=0)),
                ('answered_calls', models.IntegerField(default=0)),
                ('less_than_20_secs', models.IntegerField(default=0)),
                ('average_connection_time', models.DecimalField(decimal_places=1, default=0.0, max_digits=6)),
                ('average_wait_time', models.DecimalField(decimal_places=1, default=0.0, max_digits=6)),
            ],
        ),
    ]
