# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('incomingCalls', models.IntegerField()),
                ('answeredCalls', models.IntegerField()),
                ('lessThan20Secs', models.IntegerField()),
                ('unansweredCalls', models.IntegerField()),
                ('averageCallTime', models.DecimalField(decimal_places=1, max_digits=3)),
                ('averageQueueTime', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
