# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(default='1970-01-01', primary_key=True, serialize=False),
        ),
    ]
