# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 15:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bc_stats',
            fields=[
                ('date', models.DateField(default=datetime.date(2017, 3, 29), primary_key=True, serialize=False)),
                ('incoming_calls', models.IntegerField(default=0)),
                ('unanswered_calls', models.IntegerField(default=0)),
                ('answered_calls', models.IntegerField(default=0)),
                ('less_than_20_secs', models.IntegerField(default=0)),
                ('total_connection_time', models.IntegerField(default=0)),
                ('total_wait_time', models.IntegerField(default=0)),
                ('average_connection_time', models.DecimalField(decimal_places=1, default=0.0, max_digits=6)),
                ('average_wait_time', models.DecimalField(decimal_places=1, default=0.0, max_digits=6)),
                ('department', models.CharField(default='bc', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Stats',
            new_name='Ops_stats',
        ),
    ]
