# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0002_auto_20170329_1531'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bc_stats',
            new_name='Stats_bc',
        ),
        migrations.RenameModel(
            old_name='Ops_stats',
            new_name='Stats_ops',
        ),
    ]
