# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 11:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0003_auto_20170329_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats_bc',
            name='ivr_average_duration',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='stats_ops',
            name='ivr_average_duration',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='stats_bc',
            name='date',
            field=models.DateField(default=datetime.date(2017, 3, 30), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stats_ops',
            name='date',
            field=models.DateField(default=datetime.date(2017, 3, 30), primary_key=True, serialize=False),
        ),
    ]
