# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0004_auto_20170330_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats_bc',
            name='ivr_average_duration',
        ),
        migrations.RemoveField(
            model_name='stats_ops',
            name='ivr_average_duration',
        ),
    ]
