# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0005_auto_20170330_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats_bc',
            name='ivr_average_duration',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='stats_ops',
            name='ivr_average_duration',
            field=models.IntegerField(default=15),
        ),
    ]
