# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0006_auto_20170330_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats_bc',
            old_name='less_than_20_secs',
            new_name='fast_calls',
        ),
        migrations.RenameField(
            model_name='stats_ops',
            old_name='less_than_20_secs',
            new_name='fast_calls',
        ),
    ]
