# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0008_auto_20170405_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats_bc',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stats_ops',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, primary_key=True, serialize=False),
        ),
    ]
